CREATE TABLE `user` (
  `userID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` varchar(45) NOT NULL,
  `lastName` varchar(45) NOT NULL,
  `dateOfBirth` VARCHAR(45) NOT NULL,
   `gender` VARCHAR(45) NOT NULL,
  `phoneNumber` varchar(45) DEFAULT NULL,
  `address` varchar(45) DEFAULT NULL,
  `email` varchar(45) unique NOT NULL,
   `password` varchar(255)  NOT NULL,
   `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;



CREATE TABLE `patient` (
 `patientID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `diagnosis` VARCHAR(45) DEFAULT NULL,
  `room` INT UNSIGNED NOT NULL,
  'patient_condition' VARCHAR(45) DEFAULT 'undetermined',
  `admissionDate` date NOT NULL,
  `dischargeDate` date default NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`patientID`) REFERENCES `user`(`userID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;


CREATE TABLE `employee` (
 `employeeID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `salary` INT  DEFAULT NULL,
  `position` varchar(45) DEFAULT NULL,
  `hireDate` date NOT NULL,
  `endDate` date NOT NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`employeeID`) REFERENCES `user`(`userID`) ON DELETE RESTRICT ON 
UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;


 CREATE TABLE `patientMedicalHistory` (
  `patientMedicalHistoryID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `patientID` int UNSIGNED NOT NULL,
  `medications` varchar(100) DEFAULT NULL,
  `allergies` varchar(100) DEFAULT NULL,
  `diseases` varchar(100) DEFAULT NULL,
  `symptoms` varchar(100) DEFAULT NULL,
  `familyHistory` varchar(100) DEFAULT NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`patientMedicalHistoryID`),
  FOREIGN KEY (`patientID`) REFERENCES `patient`(`patientID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE

) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;





CREATE TABLE `prescription` (
  `prescriptionID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `medicationName` varchar(45) not NULL,
  `totalAmount` varchar(45) not NULL,
  `receivedByPatient` boolean DEFAULT FALSE,
  `prescribedAmount` varchar(45) not NULL,
  `frequency` varchar(45) not NULL,
 `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`prescriptionID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;


CREATE TABLE `note` (
  `noteID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `detail` VARCHAR(21844)  not NULL,
  `date` date  not NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`noteID`)
 ) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;

CREATE TABLE `appointment` (
  `appointmentID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_time`  time not NULL,
  `end_time`   time not NULL,
  `date`       date  not NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`appointmentID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;



CREATE TABLE `EmployeeOrdersPrescription` (
  `prescriptionID` INT UNSIGNED not NULL,
  `employeeID` int UNSIGNED not NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`employeeID`) REFERENCES `employee`(`employeeID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE,
  FOREIGN KEY (`prescriptionID`) REFERENCES `prescription`(`prescriptionID`) ON DELETE   RESTRICT ON 
  UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;



CREATE TABLE `EmployeeCreateAppointment` (
  `appointmentID` INT UNSIGNED not NULL,
  `employeeID` int UNSIGNED not NULL,
 `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`employeeID`) REFERENCES `employee`(`employeeID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE,
  FOREIGN KEY (`appointmentID`) REFERENCES `appointment`(`appointmentID`) ON DELETE   RESTRICT ON 
  UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;


CREATE TABLE `PatientHasAppointment` (
  `patientID` INT UNSIGNED not NULL,
  `appointmentID` int UNSIGNED not NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`patientID`) REFERENCES `patient`(`patientID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE,
  FOREIGN KEY (`appointmentID`) REFERENCES `appointment`(`appointmentID`) ON DELETE   RESTRICT ON 
  UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;







CREATE TABLE `employeeHasPatients` (
  `patientID`int UNSIGNED not NULL,
  `employeeID` int UNSIGNED not NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`employeeID`) REFERENCES `employee`(`employeeID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE,
  FOREIGN KEY (`patientID`) REFERENCES `patient`(`patientID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;




CREATE TABLE `patientsHasNote` (
  `patientID` int UNSIGNED not NULL,
  `noteID` int UNSIGNED not NULL,
 `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`noteID`) REFERENCES `note`(`noteID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE,
  FOREIGN KEY (`patientID`) REFERENCES `patient`(`patientID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;


CREATE TABLE `employeeWritesNote` (
  `employeeID` int UNSIGNED not NULL,
  `noteID` int UNSIGNED not NULL,
 `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`noteID`) REFERENCES `note`(`noteID`) ON DELETE RESTRICT ON
  UPDATE CASCADE,
  FOREIGN KEY (`employeeID`) REFERENCES `employee`(`employeeID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;


CREATE TABLE `PatientHasPrescription` (
  `patientID` INT UNSIGNED not NULL,
  `prescriptionID` int UNSIGNED not NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`patientID`) REFERENCES `patient`(`patientID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE,
  FOREIGN KEY (`prescriptionID`) REFERENCES `prescription`(`prescriptionID`) ON DELETE   RESTRICT ON 
  UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;



CREATE TABLE `EmployeeViewsMedicalHistory` (
  `patientMedicalHistoryID` INT UNSIGNED not NULL,
  `employeeID` int UNSIGNED not NULL,
 `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`patientMedicalHistoryID`) REFERENCES `patientMedicalHistory`(`patientMedicalHistoryID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE,
  FOREIGN KEY (`employeeID`) REFERENCES `employee`(`employeeID`) ON DELETE   RESTRICT ON 
  UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;

CREATE TABLE `PatientHasMedicalHistory` (
  `patientMedicalHistoryID` INT UNSIGNED NOT NULL,
  `patientID` int UNSIGNED NOT NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`patientMedicalHistoryID`) REFERENCES `patientMedicalHistory`(`patientMedicalHistoryID`) ON DELETE RESTRICT ON 
  UPDATE CASCADE,
  FOREIGN KEY (`patientID`) REFERENCES `patient`(`patientID`) ON DELETE   RESTRICT ON 
  UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=big5;




